### PR TITLE
Fix infinite resource updates due to canonical format conversion of resource requirements

### LINKED ISSUE #2509: CPU resource unit comparison error
## Bug Report
In Kubernetes, some resource units are automatically converted to a more convenient format internally. For example:

```yml
resources:
    limits:
      cpu: 2000m
```

Even if the CPU is set to 2000m, when you retrieve this configuration using kubectl, you might see:

```yml
resources:
    limits:
      cpu: 2
```

This indicates that the unit has been converted.

The problem arises when an Operator sets the CPU unit as `2000m`, but the Kubernetes API server keeps converting it back to `2`. This leads to a situation where, during the `DependentResource.match` process, the Operator and the API server identify the resources as different, causing `match to return false`.

스크린샷 2024-08-21 오후 5 07 14

The reason for this issue is that when comparing the actual and desired states, the values are checked through simple string comparison.

As a result, the operator keeps sending patch requests, causing the `resourceVersion` to increase infinitely.

#### Environment

`$ java -version`

17

`$ kubectl version`

v1.24

#### Possible Solution

```kotlin
Quantity("2000m") == Quantity("2")
```

In fact, when using `Quantity` in fabric8 for comparison, it can be determined that these two values are the same. It might be better to use `Quantity` for resource comparisons. However, given the current structure, this doesn't seem straightforward. Do you think it might be possible?

### PR DESCRIPTION
**Pull request by Donnerbart**
Fixes #2509

### Code coverage

* Branch `next`
  image

* Branch `bugfix/2509-ssa-matcher-quantity/next`
  image

### CODE REVIEW

File: operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/ResourceRequirementsSanitizer.java [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+ * The algorithm traverses the whole template structure because we need the actual and desired
+ * {@link Quantity} instances to compare their numerical amount. Using the
+ * {@link GenericKubernetesResource#get(Map, Object...)} shortcut would need to create new instances
+ * just for the sanitization check.
+ */
+class ResourceRequirementsSanitizer {
+
+  static void sanitizeResourceRequirements(final Map<String, Object> actualMap,
+      final PodTemplateSpec actualTemplate, final PodTemplateSpec desiredTemplate) {
+    if (actualTemplate == null || desiredTemplate == null) {
```
Comment (Donnerbart) [inline operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/ResourceRequirementsSanitizer.java:32]: I'm not 100% sure if all of these `null` checks are needed. I've added them for all fields that have no default value in their declaration.

File: operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/SSABasedGenericKubernetesResourceMatcher.java [hunk 2]
```diff
@@ -92,31 +95,26 @@ public boolean matches(R actual, R desired, Context<?> context) {
...
-    if (LoggingUtils.isNotSensitiveResource(desired)) {
-      log.trace("Original actual: \n {} \n original desired: \n {} ", actual, desiredMap);
-    }
-
     var prunedActual = new HashMap<String, Object>(actualMap.size());
     keepOnlyManagedFields(prunedActual, actualMap,
         managedFieldsEntry.getFieldsV1().getAdditionalProperties(),
         objectMapper);
 
+    var desiredMap = objectMapper.convertValue(desired, Map.class);
```
Comment (csviri) [inline operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/SSABasedGenericKubernetesResourceMatcher.java:104]: Why was this moved?

File: operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/SSABasedGenericKubernetesResourceMatcherTest.java [hunk 3]
```diff
@@ -119,52 +122,132 @@ void addedLabelInDesiredMakesMatchFail() {
...
     assertThat(sortedMap.keySet()).containsExactly("a", "b", "c");
 
-    Map<String, Object> sortedNestedMap = (Map<String, Object>) sortedMap.get("b");
+    var sortedNestedMap = (Map<String, Object>) sortedMap.get("b");
     assertThat(sortedNestedMap.keySet()).containsExactly("y", "z");
   }
+
+  @ParameterizedTest
+  @ValueSource(strings = {"sample-sts-volumeclaimtemplates-desired.yaml",
+      "sample-sts-volumeclaimtemplates-desired-with-status.yaml",
```
Comment (csviri) [inline operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/SSABasedGenericKubernetesResourceMatcherTest.java:169]: I'm a little bit more fan of building such resources in java, would be more expressive a bit, but that is jut a nit :)

**Review by csviri — APPROVED** [review]
Overall this looks good to me, just made some really minor. comments.
In future maybe we could have sanitizers customizable, like have the ability to pass only few sanitizers if there will be more.

Thank you @Donnerbart !!

File: operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/SSABasedGenericKubernetesResourceMatcher.java (hunk 2 above)
Comment (Donnerbart) [reply operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/SSABasedGenericKubernetesResourceMatcher.java:104]: The original order of method invocations jumped between pruning/sanitizing the actual and the desired resource. Just from the method names it was partially ambiguous to me which resource is changed (actual/desired, actualMap/desiredMap/prunedActual).

So I re-arranged the code into these logical groups:
* get managed fields (or throw)
* get serialization
* prepare actual -> actualMap -> prunedActual
* desired -> desiredMap
* compare prunedActual with desiredMap

By removing some of the many newlines, these logical blocks are also visually grouped together.

Comment (Donnerbart) [reply operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/SSABasedGenericKubernetesResourceMatcher.java:104]: After going through the code there might be one undesired change: When `keepOnlyManagedFields()` throws an exception, we won't see the `log.trace("Original actual: \n {} \n original desired: \n {} ", actual, desiredMap)` anymore.

If that needs to be fixed, I would suggest to move the whole `desired -> desiredMap` block before the actual block:
```java
    var objectMapper = context.getClient().getKubernetesSerialization();

    var desiredMap = objectMapper.convertValue(desired, Map.class);
    if (LoggingUtils.isNotSensitiveResource(desired)) {
      log.trace("Original actual:\n {}\n original desired:\n {}", actual, desiredMap);
    }
    removeIrrelevantValues(desiredMap);

    var actualMap = objectMapper.convertValue(actual, Map.class);
    sanitizeState(actual, desired, actualMap);
    var prunedActual = new HashMap<String, Object>(actualMap.size());
    keepOnlyManagedFields(prunedActual, actualMap,
        managedFieldsEntry.getFieldsV1().getAdditionalProperties(),
        objectMapper);

    var matches = prunedActual.equals(desiredMap);
```

File: operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/SSABasedGenericKubernetesResourceMatcherTest.java (hunk 3 above)
Comment (Donnerbart) [reply operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/SSABasedGenericKubernetesResourceMatcherTest.java:169]: We're using the fabric8 builder classes in our operator tests a lot, but sometimes I think the nested builders are harder to read (heavily depending on the code formatter settings). For example, using `.withNewTemplate()` the nested `.withNewSpec()/endSpec()` are often intended on the same level as the outer `.withNewSpec()/endSpec()` from the STS, which I personally find much harder to read than a well formatted XML file. This can be mitigated by using `.withTemplate(new PodTemplateSpecBuilder()...build())` though.

I just had a look how e.g. `sample-sts-volumeclaimtemplates.yaml` would look like in Java code:
```java
    var actualStatefulSet = new StatefulSetBuilder()
        .withNewMetadata()
        .withName("test")
        .withUid("50913e35-e855-469f-bec6-3e8cd2607ab4")
        .withManagedFields(new ManagedFieldsEntryBuilder()
            .withManager("controller")
            .withOperation("Apply")
            .withApiVersion("apps/v1")
            .withTime("2024-10-24T19:15:25Z")
            .withNewFieldsV1()
             ???
            .endFieldsV1()
            .build())
        .endMetadata()
        .withNewSpec()
        .withReplicas(1)
        .withNewSelector().addToMatchLabels("app", "test-app").endSelector()
        .withServiceName("nginx-service")
        .withTemplate(new PodTemplateSpecBuilder()
            .withNewMetadata().addToLabels("app", "test-app").endMetadata()
            .withNewSpec()
            .addNewContainer()
            .withName("nginx")
            .withImage("nginx:1.17.0")
            .addNewPort().withContainerPort(80).endPort()
            .addNewVolumeMount()
            .withName("persistent-storage")
            .withMountPath("/usr/share/nginx/html")
            .endVolumeMount()
            .endContainer()
            .endSpec()
            .build())
        .addToVolumeClaimTemplates(new PersistentVolumeClaimBuilder()
            .withNewMetadata().withName("persistent-storage").endMetadata()
            .withNewSpec()
            .addToAccessModes("ReadWriteOnce")
            .withNewResources()
            .addToRequests("storage", new Quantity("1Gi"))
            .endResources()
            .withStorageClassName("standard")
            .withVolumeMode("Filesystem")
            .endSpec()
            .withNewStatus()
            .withPhase("Pending")
            .endStatus()
            .build())
        .endSpec()
        .build();
```
I gave up on the managed fields. Without looking up an example in the fabric8 client I have no idea how to use that builder. I already had to guess how to write that correctly in XML, by adapting this from another resource file :sweat_smile:

So even as a heavy user of those builder classes, I think for these complex resources XML files are easier to write and even to compare (IDEA -> mark two files -> diff).

File: operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/SSABasedGenericKubernetesResourceMatcher.java (hunk 2 above)
Comment (Donnerbart) [reply operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/SSABasedGenericKubernetesResourceMatcher.java:104]: Or we could also align what we print in that trace log:
```java
    var objectMapper = context.getClient().getKubernetesSerialization();
    var actualMap = objectMapper.convertValue(actual, Map.class);
    var desiredMap = objectMapper.convertValue(desired, Map.class);
    if (LoggingUtils.isNotSensitiveResource(desired)) {
      log.trace("Original actual:\n {}\n original desired:\n {}", actualMap, desiredMap);
    }

    sanitizeState(actual, desired, actualMap);
    var prunedActual = new HashMap<String, Object>(actualMap.size());
    keepOnlyManagedFields(prunedActual, actualMap,
        managedFieldsEntry.getFieldsV1().getAdditionalProperties(),
        objectMapper);

    removeIrrelevantValues(desiredMap);

    var matches = prunedActual.equals(desiredMap);
```
I think this is even more readable.

**Comment by csviri** [comment]
I guess this needs a rebase. Sorry I'm on out this and partially next week. @metacosm  from my side this PR can go in after rebase, pls review it also.

File: operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/SSABasedGenericKubernetesResourceMatcher.java (hunk 2 above)
Comment (Donnerbart) [reply operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/SSABasedGenericKubernetesResourceMatcher.java]: Since I anyway had to rebase, I changed the code to the last variant to restore the order of execution, but switched to `actualMap` for the trace logging (I think it'll be much easier to read if both resources are logged in the same format).

**Comment by Donnerbart** [comment]
Rebase is done.

**Review by csviri — APPROVED** [review]

**Comment by metacosm** [comment]
Sorry, I should have merged this before rebasing next. Apologies for the extra work that was bad scheduling on my part. 🙍

**Review by metacosm — APPROVED** [review]
Thank you!
