### PR TITLE
fix: delete CRD only after all tests in the class pass

### LINKED ISSUE #2928: [Junit extension] Delete CRD only after All test not each
Deleting CRD after each test case does not make sense, and causes all subsequent tests to fail after one test case failed since CRD stays in "deleting" state.

### PR DESCRIPTION
**Pull request by xstefank**
Fixes #2928

### CODE REVIEW

**Comment by xstefank** [comment]
@csviri I wasn't sure if you mean after all tests or after test class, so I did a after a test class first, but I can move it to after testsuite.

**Comment by xstefank** [comment]
@csviri this is ready for review

**Comment by csviri** [comment]
thx @xstefank , will take a look tomorrow; but was thinking if we should target `next` branch, since it is change in the behavior (not super important though)

**Review by csviri — APPROVED** [review]
nice! LGTM

File: operator-framework-junit/src/main/java/io/javaoperatorsdk/operator/junit/LocallyRunOperatorExtension.java [hunk 1]
```diff
@@ -387,12 +392,27 @@ protected void after(ExtensionContext context) {
...
 
-  private void deleteCrd(AppliedCRD appliedCRD, KubernetesClient client) {
-    if (!deleteCRDs) {
-      LOGGER.debug("Skipping deleting CRD because of configuration: {}", appliedCRD);
-      return;
+  private static class CrdCleanup implements ExtensionContext.Store.CloseableResource {
+    @Override
+    public void close() {
+      // Create a fresh client for cleanup since operator clients may already be closed.
+      try (var client = new KubernetesClientBuilder().build()) {
```
Comment (metacosm) [inline operator-framework-junit/src/main/java/io/javaoperatorsdk/operator/junit/LocallyRunOperatorExtension.java:399]: Isn't it the role of the infrastructure client to perform these operations?

Comment (xstefank) [reply operator-framework-junit/src/main/java/io/javaoperatorsdk/operator/junit/LocallyRunOperatorExtension.java:399]: no, because this method runs after `@After` method that closes the infrastructure client.
